import os
import platform

if platform.system() == 'Windows':
    stellaris_path = "C:/Program Files (x86)/Steam/steamapps/workshop/content/281990/"
elif platform.system() == 'Linux':
    stellaris_path = os.environ["HOME"] + "/.local/share/Steam/steamapps/workshop/content/281990/"

if platform.system() == 'Windows':
    stellaris_game_path = "C:/Program Files (x86)/Steam/steamapps/common/Stellaris/"
elif platform.system() == 'Linux':
    stellaris_game_path = os.environ["HOME"] + "/.local/share/Steam/steamapps/common/Stellaris/"

file_prefix = "zzzzzzzzzzzzzzzzzzzz_" # file prefix for autogenerated files

aot_modid = "2178603631" # Acquisition of Technologies modid
mr_modid = "2807759164" # Merger of Rules modid
aup_modid = '1995601384' # unofficial patch 
giga_modid = '1121692237' # gigastructure

# Default mod excludes
mod_excludes = [
]


# +++++++++++++++++ #
# PLEASE EDIT BELOW #
# +++++++++++++++++ #

# Please write every large mod that is NOT used in the current playset.
mod_excludes += [
    '2417206619', # Wandering Witch
    '2529002857', # production revolution
    '2830366252', # production revolution patch
    '2466607238' # Kasako framework
] # TODO: load irony/stellaris launcher database to obtain excludes

# mod_order is the dictionary of pairs of job name and mod id, suggesting which job definition associating with the mod is used in case of the job definition conflict.
# If there is any mod conflict, the program will give some instruction to edit this field.
mod_order =  {
    b'gpm_archaeologist': '2807759164', 
    b'gpm_archaeologist_drone': '2807759164', 
    b'gpm_precursor_archaeologist': '2807759164', 
    b'gpm_precursor_archaeologist_drone': '2807759164', 
    b'gpm_orbital_researcher': '2807759164', 
    b'gpm_orbital_researcher_drone': '2807759164', 
    b'archaeoengineers': '865040033', 
    b'criminal': '2785989313', 
    b'acot_researcher': '2807759164', 
    b'acot_researcher_drone': '2807759164',
     b'acot_priest': '2807759164', 
     b'acot_transmute_drone': '2807759164', 
     b'acot_voidsphere_labman': '2807759164', 
     b'acot_voidsphere_labdrone': '2807759164', 
     b'acot_free_thinker': '2807759164', 
     b'ae_researcher': '2807759164', 
     b'ae_researcher_drone': '2807759164', 
     b'phanon_researcher': '2807759164', 
     b'phanon_researcher_drone': '2807759164', 
     b'phanon_priest': '2807759164', 
     b'stellarite_researcher': '2807759164', 
     b'stellarite_researcher_drone': '2807759164', 
     b'stellarite_priest': '2807759164',
     b'stellarite_bureaucrat': '2807759164', 
     b'organic_battery': '1311725711'
}