# +++++++++++++++++ #
# DO NOT EDIT BELOW #
# +++++++++++++++++ #

import os
import platform
import json
import glob

with open(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "exported.json")
) as f:
    mod_load_list_json = json.load(f)

if platform.system() == "Windows":
    stellaris_path = "C:/Program Files (x86)/Steam/steamapps/workshop/content/281990/"
elif platform.system() == "Linux":
    stellaris_path = (
        os.environ["HOME"] + "/.local/share/Steam/steamapps/workshop/content/281990/"
    )

if platform.system() == "Windows":
    stellaris_game_path = "C:/Program Files (x86)/Steam/steamapps/common/Stellaris/"
elif platform.system() == "Linux":
    stellaris_game_path = (
        os.environ["HOME"] + "/.local/share/Steam/steamapps/common/Stellaris/"
    )

mod_installed = set(
    [os.path.basename(x) for x in glob.glob(os.path.join(stellaris_path, "*"))]
)
mod_loaded = set(
    [str(i["SteamId"]) for i in mod_load_list_json["ModIds"] if i["SteamId"]]
)

file_prefix = "zzzzzzzzzzzzzzzzzzzz_"  # file prefix for autogenerated files

aot_modid = "2178603631"  # Acquisition of Technologies modid
mr_modid = "2807759164"  # Merger of Rules modid
aup_modid = "1995601384"  # unofficial patch
giga_modid = "1121692237"  # gigastructure

# Default mod excludes
mod_excludes = list(mod_installed - mod_loaded)

mod_excludes += [
    "2529002857",  # production revolution SHOULD BE DISABLED
    "2830366252",  # production revolution patch SHOULD BE DISABLED
    "2466607238",  # Kasako framework SHOULD BE DISABLED
]  # TODO: load irony/stellaris launcher database to obtain excludes

# +++++++++++++++++ #
# PLEASE EDIT BELOW #
# +++++++++++++++++ #

# mod_order is the dictionary of pairs of job name and mod id, suggesting which job definition associating with the mod is used in case of the job definition conflict.
# If there is any mod conflict, the program will give some instruction to edit this field.
mod_order = {
    b"fe_overseer": "1995601384",
    b"fe_sky_cardinal": "1995601384",
    b"fe_guardian_bot": "1995601384",
    b"fe_protector": "1995601384",
    b"fe_archivist": "1995601384",
    b"fe_acolyte_farm": "1995601384",
    b"fe_acolyte_mine": "1995601384",
    b"fe_acolyte_generator": "1995601384",
    b"fe_augur": "1995601384",
    b"fe_xeno_keeper": "1995601384",
    b"fe_xeno_ward": "1995601384",
    b"fe_hedonist": "1995601384",
    b"fe_acolyte_artisan": "1995601384",
    b"fe_maintenance_bot": "1995601384",
    b"researcher": "1995601384",
    b"xeno_zoo_keeper": "1995601384",
    b"priest": "1995601384",
    b"death_priest": "1995601384",
    b"enforcer": "1995601384",
    b"telepath": "1995601384",
    b"entertainer": "1995601384",
    b"duelist": "1995601384",
    b"culture_worker": "1995601384",
    b"bureaucrat": "1995601384",
    b"unifier": "1995601384",
    b"chemist": "1995601384",
    b"translucer": "1995601384",
    b"gas_refiner": "1995601384",
    b"roboticist": "1995601384",
    b"healthcare": "1995601384",
    b"trader": "1995601384",
    b"numistic_priest": "1995601384",
    b"manager": "1995601384",
    b"steward": "1995601384",
    b"necromancer": "1995601384",
    b"bluelotus_technician": "1995601384",
    b"death_chronicler": "1995601384",
    b"necro_apprentice": "1995601384",
    b"foundry": "1995601384",
    b"catalytic_technician": "1995601384",
    b"artisan": "1995601384",
    b"artificer": "1995601384",
    b"pearl_diver": "1995601384",
    b"reassigner": "1995601384",
    b"bath_attendant": "1995601384",
    b"knight": "1995601384",
    b"archaeoengineers": "865040033",
    b"event_purge": "1995601384",
    b"ratling_scavenger": "1995601384",
    b"odd_factory_worker": "1995601384",
    b"odd_factory_drone": "1995601384",
    b"underground_trade_worker": "1995601384",
    b"underground_contact_drone": "1995601384",
    b"dimensional_portal_researcher": "1995601384",
    b"dimensional_portal_researcher_gestalt": "1995601384",
    b"space_time_anomaly_researcher": "1995601384",
    b"space_time_anomaly_researcher_gestalt": "1995601384",
    b"gas_plant_engineer": "1995601384",
    b"gas_plant_engineer_gestalt": "1995601384",
    b"cave_cleaner": "1995601384",
    b"cave_cleaner_gestalt": "1995601384",
    b"titan_hunter": "1995601384",
    b"robot_caretaker": "1995601384",
    b"turtle_miner": "1995601384",
    b"turtle_miner_gestalt": "1995601384",
    b"machine_nurse": "1995601384",
    b"manufactorium_specialist": "1995601384",
    b"manufactorium_complex_drone": "1995601384",
    b"manufactorium_scraper": "1995601384",
    b"manufactorium_scraper_drone": "1995601384",
    b"archivist": "1995601384",
    b"puddle_technician": "1995601384",
    b"puddle_technician_drone": "1995601384",
    b"stasis_warden": "1995601384",
    b"stasis_warden_drone": "1995601384",
    b"astrogarbage_collector": "1995601384",
    b"astrogarbage_collector_gestalt": "1995601384",
    b"myrmeku_power_farmer": "1995601384",
    b"myrmeku_power_farmer_gestalt": "1995601384",
    b"stratovent_researcher": "1995601384",
    b"stratovent_refiner": "1995601384",
    b"stratovent_refiner_upg": "1995601384",
    b"stratovent_refiner_minerals": "1995601384",
    b"colonist": "1995601384",
    b"clerk": "1995601384",
    b"technician": "1995601384",
    b"miner": "1995601384",
    b"crystal_miner": "1995601384",
    b"gas_extractor": "1995601384",
    b"mote_harvester": "1995601384",
    b"farmer": "1995601384",
    b"soldier": "1995601384",
    b"preacher": "1995601384",
    b"mortal_initiate": "1995601384",
    b"scrap_miner": "1995601384",
    b"angler": "1995601384",
    b"ranger": "1995601384",
    b"squire": "1995601384",
    b"spawning_drone": "1311725711",
    b"offspring_drone": "1311725711",
    b"cyber_drone": "1311725711",
    b"replicator": "1311725711",
    b"crucible_drone": "1311725711",
    b"coordinator": "1311725711",
    b"evaluator": "1311725711",
    b"synapse_drone": "1311725711",
    b"brain_drone": "1311725711",
    b"calculator": "1311725711",
    b"artisan_drone": "1311725711",
    b"fabricator": "1311725711",
    b"alloy_drone": "1311725711",
    b"catalytic_drone": "1311725711",
    b"chemist_drone": "1311725711",
    b"translucer_drone": "1311725711",
    b"gas_refiner_drone": "1311725711",
    b"patrol_drone": "1311725711",
    b"crystal_mining_drone": "1311725711",
    b"mote_harvesting_drone": "1311725711",
    b"gas_extraction_drone": "1311725711",
    b"mining_drone": "1311725711",
    b"agri_drone": "1311725711",
    b"technician_drone": "1311725711",
    b"maintenance_drone": "1311725711",
    b"warrior_drone": "1311725711",
    b"bluelotus_drone": "1311725711",
    b"chronicle_drone": "1311725711",
    b"scrap_miner_drone": "1311725711",
    b"bath_attendant_hive": "1311725711",
    b"bath_attendant_machine": "1311725711",
    b"archaeo_drone": "1311725711",
    b"archaeo_unit": "1311725711",
    b"servant": "1995601384",
    b"slave_overseer": "1995601384",
    b"slave_toiler": "1995601384",
    b"organic_battery": "1311725711",
    b"livestock": "1995601384",
    b"livestock_zoo_animal": "1995601384",
    b"livestock_zoo_beast": "1995601384",
    b"bio_trophy": "1995601384",
    b"purge": "1995601384",
    b"crisis_purge": "1995601384",
    b"assimilation": "1995601384",
    b"criminal": "1995601384",
    b"deviant_drone": "1995601384",
    b"corrupt_drone": "1995601384",
    b"fotd_protectors": "1995601384",
    b"gpm_archaeologist": "2807759164",
    b"gpm_archaeologist_drone": "2807759164",
    b"gpm_precursor_archaeologist": "2807759164",
    b"gpm_precursor_archaeologist_drone": "2807759164",
    b"gpm_orbital_researcher": "2807759164",
    b"gpm_orbital_researcher_drone": "2807759164",
    b"acot_researcher": "2807759164",
    b"acot_researcher_drone": "2807759164",
    b"acot_priest": "2807759164",
    b"acot_transmute_drone": "2807759164",
    b"acot_voidsphere_labman": "2807759164",
    b"acot_voidsphere_labdrone": "2807759164",
    b"acot_free_thinker": "2807759164",
    b"ae_researcher": "2807759164",
    b"ae_researcher_drone": "2807759164",
    b"dummicist": "2807759164",
    b"matter_reanimator": "2807759164",
    b"phanon_researcher": "2807759164",
    b"phanon_researcher_drone": "2807759164",
    b"phanon_priest": "2807759164",
    b"stellarite_researcher": "2807759164",
    b"stellarite_researcher_drone": "2807759164",
    b"stellarite_priest": "2807759164",
    b"stellarite_bureaucrat": "2807759164",
}
